{
  config,
  lib,
  pkgs,
  ...
}: {
  imports = [
    ./alacritty.nix
    ./carapace.nix
    ./chromium.nix
    ./firefox.nix
    ./git.nix
    ./kitty.nix
    ./librewolf.nix
    ./mangohud.nix
    ./minecraft-servers.nix
    ./neovim.nix
    ./nushell.nix
    ./packages.nix
    ./rider.nix
    ./spotify.nix
    ./starship.nix
    ./thefuck.nix
    ./unp.nix
    ./vencord.nix
    ./vesktop.nix
    ./vscode.nix
    ./waybar.nix
    ./wofi.nix
    ./zen-browser.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}
